### PR TITLE
Created function #9

### LINKED ISSUE #9: Create a function that calculates the sum of two numbers
Create a Python file and write in it a function that takes two integers and returns their sum.

### PR DESCRIPTION
**Pull request by toby016**
### Describe my changes

created a function that reads two integers and returns their sum.

### CODE REVIEW

**Review by rochdikhalid — CHANGES_REQUESTED** [review]
Thank you @toby016 . Logically, your function works. But, you need to call it and give it the information (numbers) that needs to calculate and print the sum.

**Comment by toby016** [comment]
added:
call it and give it the sample arguments and print out the results.

**Review by rochdikhalid — APPROVED** [review]
Good job.

**Comment by toby016** [comment]
sorry, I am not so familiar with GitHub and I find out when I push all my changes from my repository. Even I linked issue 11, it still appears here. and in issue 11, it only states "referenced". Am I doing it wrongly? thank you in advance and sorry about any inconvenience that may have caused.

**Comment by rochdikhalid** [comment]
You are doing a good job and your issue is closed automatically #9. We are here to make mistakes and learn. So, feel free to make them.

**Pull request merged**
