### PR TITLE
Fix: #3

### LINKED ISSUE #3: Create HomePage HTML
Build a home page with HTML.  Come up with an idea and run with it!

### PR DESCRIPTION
**Pull request by toby016**
## Describe your changes
- create html for homepage (draft, very appreciate if any constructive feedback is raised)
- cannot successfully link photo to webpage (have tried many ways but unable to do so, could anyone help and fix that? thanks)
- add the logo created earlier to here

## Issue ticket number 
#3

### CODE REVIEW

**Comment by BenJensen2** [comment]
@toby016 Thanks for working on this. The reason for the photo not linking is that your image source needs to be a location in the repo. You currently have it as a url link to the location in your personal repo

The location should be a relative file location starting with the location of the html file.

Looking at your personal repo. The image tag should have a src of "bigger_version_logo.png"

That should fix it. Go ahead and make that commit and pull request then I can approve it

**Comment by SushanthReddy-49** [comment]
Hi, @BenJensen2 I made the changes to the Image SRC, and now the image is rendering as expected.

**Comment by BenJensen2** [comment]
@SushanthReddy-49 Awesome, go ahead and submit a new PR with the changes and I can approve it

**Comment by SushanthReddy-49** [comment]
Hey @BenJensen2 changes are committed now you can merge this PR.

**Review by SushanthReddy-49 — APPROVED** [review]

**Pull request merged**
